# Generated by Django 5.0.6 on 2024-06-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploadingdate", models.DateTimeField(auto_now=True)),
                ("Description", models.CharField(max_length=100, null=True)),
                ("Name", models.CharField(max_length=30, null=True)),
                ("File", models.FileField(null=True, upload_to="")),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
